name: release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: install deps
        run: yarn install
      - name: build docs
        run: |
          rm -rf out
          git worktree prune
          git fetch origin gh-pages:gh-pages
          git worktree add out gh-pages
          yarn build:ci
          cp -r out/tmp/* out
          rm -rf out/tmp

      - uses: salesforcecli/github-workflows/.github/actions/gitConfig@main
        with:
          username: "svc-cli-bot-jsforce"
          email: "svc_cli_bot@salesforce.com"
      - name: send to git
        run: |
          cd out
          git add .
          git commit -m 'docs: publishing gh-pages [skip ci]' --no-verify
          git push origin gh-pages --no-verify
